--- #YAML:1.0
name:               HTML-Clean-Human
version:            1.07
abstract:           html syntax cleaner and reformatter for human beings
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:             2.12
    Exporter:           5
    File::Which:        0.05
    HTML::Entities:     1.35
    LEOCHARRE::Class2:  1.12
    LEOCHARRE::CLI:     1.18
    Smart::Comments:    1
    Test::Simple:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
