--- #YAML:1.0
name:                HTML-Clean-Human
version:             1.06
abstract:            ~
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Encode:                        2.12
    Exporter:                      5
    File::Which:                   0.05
    HTML::Entities:                1.35
    LEOCHARRE::Class2:             1.12
    LEOCHARRE::CLI:                1.18
    Smart::Comments:               1
    Test::Simple:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
